# **Задание на повторение материала
#### 1) Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно

In [1]:
import numpy as np
a = np.arange(12, 24)
print(a)

[12 13 14 15 16 17 18 19 20 21 22 23]


#### 2) Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1.

In [2]:
list_a = [a.reshape(i, len(a)//i) for i in range(1, len(a)+1) if len(a)%i == 0]
print(*list_a[:5], sep='\n\n')

[[12 13 14 15 16 17 18 19 20 21 22 23]]

[[12 13 14 15 16 17]
 [18 19 20 21 22 23]]

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]

[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]

[[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]


#### 3) Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для строк).

In [3]:
a1 = a.reshape(2, -1)
a2 = a.reshape(3, -1)
a3 = a.reshape(4, -1)

a4 = a.reshape(-1, 2)
a5 = a.reshape(-1, 1)

print(a1, a2, a3, a4, a5, sep='\n\n')

[[12 13 14 15 16 17]
 [18 19 20 21 22 23]]

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]

[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]

[[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]

[[12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]


#### 4) Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?
Нет т.к. это двумерный массив, в котором по 1 значению в строке. Пример выше (последний массив в задании 3).

#### 5) Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.

In [4]:
a = np.random.randn(3, 4)
b = a.flatten()
print(a, a.size)
print(b, b.size)

[[ 1.32330779  1.1790265  -0.26485716  0.53768019]
 [-0.71541672 -1.81672274  0.30749153  0.31715559]
 [-1.69192938 -0.84041007  1.6857492  -0.14304353]] 12
[ 1.32330779  1.1790265  -0.26485716  0.53768019 -0.71541672 -1.81672274
  0.30749153  0.31715559 -1.69192938 -0.84041007  1.6857492  -0.14304353] 12


#### 6) Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2.

In [5]:
a = np.arange(20, 0, -2)
print(a)

[20 18 16 14 12 10  8  6  4  2]


#### 7) Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2. В чем разница между массивами a и b?

In [6]:
b = np.arange(20, 1, -2).reshape(-1, 1)
print(b)

[[20]
 [18]
 [16]
 [14]
 [12]
 [10]
 [ 8]
 [ 6]
 [ 4]
 [ 2]]


2. Массив a - одномерный, b - двумерный

#### 8) Вертикально соединить массивы a и b. a - двумерный массив из нулей, число строк которого больше 1 и на 1 меньше, чем число строк двумерного массива b, состоящего из единиц. Итоговый массив v должен иметь атрибут size, равный 10.

In [7]:
a = np.zeros((2, 2))
b = np.ones((3, 2))
v = np.vstack((a, b))
print(v, v.size)

[[0. 0.]
 [0. 0.]
 [1. 1.]
 [1. 1.]
 [1. 1.]] 10


#### 9) Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12. Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), состоящая из 4 строк и 3 столбцов. Получить матрицу At путем транспонирования матрицы A. Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения. Какой размер имеет матрица B?

In [8]:
a = np.arange(0, 12)
print(a)

A = a.reshape(4, 3)
print(A)

At = A.T
print(At)

B = np.matmul(A, At)
print(B, B.size, np.linalg.det(B))

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]
[[  5  14  23  32]
 [ 14  50  86 122]
 [ 23  86 149 212]
 [ 32 122 212 302]] 16 0.0


Получится ли вычислить обратную матрицу для матрицы B и почему?
Не получится т.к. опредилитель = 0
#### 10) Инициализируйте генератор случайных числе с помощью объекта seed, равного 42.

In [9]:
np.random.seed(42)

#### 11) Создайте одномерный массив c, составленный из последовательности 16-ти случайных равномерно распределенных целых чисел от 0 до 16 невключительно. 

In [10]:
c = np.random.randint(0, 16, 16)
print(c)

[ 6  3 12 14 10  7 12  4  6  9  2  6 10 10  7  4]


#### 12) Поменяйте его форму так, чтобы получилась квадратная матрица C. Получите матрицу D, поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, умноженной на 10. Вычислите определитель, ранг и обратную матрицу D_inv для D.

In [11]:
C = c.reshape(4, 4)
D = B + C * 10
print(np.linalg.det(D), np.linalg.matrix_rank(D))

D_inv = np.linalg.inv(D)
print(D_inv)

-28511999.999999944 4
[[ 0.00935396  0.04486532  0.05897517 -0.07286055]
 [-0.01503577 -0.00122896 -0.00192971  0.00967873]
 [-0.00356692 -0.01782828 -0.04152146  0.04326178]
 [ 0.00909091 -0.00181818  0.01272727 -0.01090909]]


#### 13) Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице. Убедитесь, что в матрице D_inv остались только нули и единицы. С помощью функции numpy.where, используя матрицу D_inv в качестве маски, а матрицы B и C - в качестве источников данных, получите матрицу E размером 4x4.  Элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 1, должны быть равны соответствующему элементу матрицы B, а элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 0, должны быть равны соответствующему элементу матрицы C.

In [12]:
D_inv[D_inv <= 0] = 0
D_inv[D_inv > 0] = 1
E = np.where(D_inv == 1, B, C)
print(B, C, D_inv, E, sep='\n\n')

[[  5  14  23  32]
 [ 14  50  86 122]
 [ 23  86 149 212]
 [ 32 122 212 302]]

[[ 6  3 12 14]
 [10  7 12  4]
 [ 6  9  2  6]
 [10 10  7  4]]

[[1. 1. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [1. 0. 1. 0.]]

[[  5  14  23  14]
 [ 10   7  12 122]
 [  6   9   2 212]
 [ 32  10 212   4]]
